# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    backend "s3" {
        bucket  = "apps-tf-states-bucket"
        key     = "./terraform.tfstate"
        region  = "us-east-1"
        encrypt = true
    }
}
